name: coverage_service
description: A simple service that give you the test coverage of your application
version: 0.1.0
homepage: https://github.com/rushio-consulting/coverage_service
author: Rushio Consulting <dev@rushio-consulting.fr>

environment:
  sdk: '>=2.1.0 <3.0.0'

executable:
  coverage_cli: main
  coverage_server: server

dependencies:
  grpc: ^1.0.2
  protobuf: ^0.13.11
  logging: ^0.11.3+2
  uuid: ^2.0.1
  archive: ^2.0.8
  pedantic: ^1.0.0
  build_cli_annotations: ^1.1.0
  yaml: ^2.1.15
  mockito: ^4.0.0


dev_dependencies:
  test: ^1.0.0
  build_cli: ^1.3.2
  build_runner: ^1.0.0
